#!/bin/bash

# Script to check that the IPs HAProxy is listening on are also listed in the keepalived config

HACONFIGFILE="/etc/haproxy/haproxy.cfg"
TEMPFILE=`mktemp`

# Find all the 'listen' and 'frontend' lines from the haproxy configuration, and extract the IP address
egrep '(listen|frontend)' $HACONFIGFILE | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' | grep -v 127.0.0.1 > $TEMPFILE

# Remove duplicates
sort $TEMPFILE | uniq

# Tidy up
rm -f $TEMPFILE
